export {Main} from "./Main"
export {Footer} from "./Footer"
export {Menu} from "../../Menu"
export {Reservations} from "../../Reservations"
export {OrderOnline} from "../../OrderOnline"
export {Login} from "../../Login"